# Generated by Django 2.1.15 on 2020-04-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200128_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('about', models.TextField(max_length=400)),
                ('food_minimum', models.FloatField()),
                ('delivery_fee', models.FloatField()),
                ('is_delivery', models.BooleanField(default=True)),
            ],
        ),
    ]
