# Generated by Django 2.1.15 on 2020-05-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200429_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_fee',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='food_minimum',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_delivery',
            field=models.CharField(max_length=200),
        ),
    ]
