# Generated by Django 2.1.15 on 2020-01-21 22:31

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191226_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
