# Generated by Django 2.1.15 on 2020-01-21 22:41

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200121_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=s3direct.fields.S3DirectField(),
        ),
    ]
