# Generated by Django 2.1.15 on 2020-01-22 04:52

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200122_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
