# Generated by Django 2.2.7 on 2020-01-22 05:11

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200122_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
