# Generated by Django 2.1.15 on 2020-01-22 14:12

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200122_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', s3direct.fields.S3DirectField(blank=True)),
            ],
        ),
    ]
