# Generated by Django 2.1.15 on 2020-01-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
